### ISSUE TITLE
Filtering by string values in SPARQL

### ISSUE THREAD

**Issue by sklarman** [epistemik-co/staple-api#59]
Currently the filtering of string-valued properties in SPARQL is done via a pattern:

```
?x <http://www.w3.org/2000/01/rdf-schema#label> "Elizabeth II" .
```

However, sometimes strings in RDF are additionally annotated with language tags, as in:
```
<http://dbpedia.org/resource/Elizabeth_II> <http://www.w3.org/2000/01/rdf-schema#label> "Elizabeth II"@en .
```

Our filtering pattern fails to pick up on these kind of cases. Besides, we might have also cases when we want to allow several different possible string values. So we should change this to the following pattern:

```
?x <http://www.w3.org/2000/01/rdf-schema#label> ?y .
FILTER(str(?y) in ( "Elizabeth II", "Elizabeth I", ... ))
```

**Comment by anvime** [comment]
bug fix branch merged
